//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3 {
    
    
    public partial class WebForm2 {
        
        /// <summary>
        /// OlapChart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dundas.Olap.WebUIControls.OlapChart OlapChart1;
        
        /// <summary>
        /// AdomdNetDataProvider1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dundas.Olap.Data.AdomdNet.AdomdNetDataProvider AdomdNetDataProvider1;
        
        /// <summary>
        /// OlapChart2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dundas.Olap.WebUIControls.OlapChart OlapChart2;
        
        /// <summary>
        /// AdomdDataProvider1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Dundas.Olap.Data.Adomd.AdomdDataProvider AdomdDataProvider1;
    }
}
